### PR TITLE
#99 Remove old graphql codegen config

### PR DESCRIPTION
**Pull request by nevendyulgerov**

### CODE REVIEW

**Comment by dandheedge** [comment]
@nevendyulgerov please rebase the PR

**Comment by brunomenezes** [comment]
@nevendyulgerov, 
It looks good! It needs a rebase though

**Review by brunomenezes — CHANGES_REQUESTED** [review]
@nevendyulgerov, 
It looks good! It needs a rebase though.

**Comment by nevendyulgerov** [comment]
Hey @brunomenezes , I rebased to `main`, however I got some 'residue' from the PRs for the mantine update and removal of custom Card component, not sure why though, maybe it's related to the git hash problem you mentioned on the daily.

**Review by brunomenezes — APPROVED** [review]

**Comment by brunomenezes** [comment]
> Hey @brunomenezes , I rebased to `main`, however I got some 'residue' from the PRs for the mantine update and removal of custom Card component, not sure why though, maybe it's related to the git hash problem you mentioned on the daily.

Yeah, probably! were they empty conflicts you need to "solve"?

**Pull request merged**
