### PR TITLE
Chain selection

### PR DESCRIPTION
**Pull request by tuler**
Only 1 chain is supported, depending on the `NEXT_PUBLIC_CHAIN_ID` env var, as we will have one deployed per network.

I also added the connect button to the header, but we need to investigate how to integrate Mantine theme into the RainbowKit theme.
https://www.rainbowkit.com/docs/theming
https://www.rainbowkit.com/docs/custom-theme

ps: also bumped mantine to new beta.

### CODE REVIEW

**Comment by brunomenezes** [comment]
Just need to add this env var on Vercel projects and I think it is all good.

**Comment by tuler** [comment]
The button is very ugly.
Maybe I should hide it for now, and then research how to make it look good (follow Matine theme).

**Comment by brunomenezes** [comment]
> The button is very ugly. Maybe I should hide it for now, and then research how to make it look good (follow Matine theme).

Yeah, since we are not using it. I agree that we are better off without it. Also, agree that it currently feels out of place.

**Comment by tuler** [comment]
> Yeah, since we are not using it. I agree that we are better off without it. Also, agree that it currently feels out of place.

I made it look better, I think we can merge with it.

**Review by brunomenezes — APPROVED** [review]

**Pull request merged**
